apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-app
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/keicee/pg-data
    type: DirectoryOrCreate
