apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story-app
  template:
    metadata:
      labels:
        app: story-app
    spec:
      containers:
        - name: story-app
          image: keicee32/story-app-volumes
          volumeMounts:
            - mountPath: /storage
              name: storage-volume
      volumes:
        - name: storage-volume
          emptyDir: {}
            #sizeLimit: 500Mi
