apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-story
spec:
  volumeName: pv-story
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
